lesson_01/README.md

feat: adds lesson_01 prework

---

lesson_01/README.md

chore: adds lesson_01 homework details

---

lesson_02/README.md

feat: adds lesson_02 pre-work

---

lesson_03/README.md

chore: add lesson_03 pre-work

---

.github/workflows/check_lesson_02_pr.yaml

chore: lesson 2 build checks

---

.github/workflows/check_lesson_03_pr.yaml
.github/workflows/check_push.yml

chore: adds missing build checks

---

.github/workflows/check_lesson_02_pr.yaml

chore: update lesson_02 build action

---

lesson_04/README.md
lesson_04/anthonydmays/README.md
lesson_05/README.md

feat: adds lesson_04 homework and lesson_05 pre-work

---

lesson_01/oliviajames/index.html
lesson_01/oliviajames/styles.css

lesson 01 update

---

lesson_05/README.md
lesson_06/README.md

- **feat: adds lesson_05 homework and lesson_06 pre-work**
- **chore: fix capitalization**

feat: adds lesson_05 homework and lesson_06 pre-work

---

lib/javascript/quiz-app/src/lib/prisma.ts

fix: updates prisma global type

---

lib/javascript/quiz-app/package.json

fix: regenerates prisma client on build

---

lib/javascript/quiz-app/src/app/vote/[promptId]/page.tsx

fix: redirects to correct results page

---

.github/workflows/check_lesson_06_quiz.yaml

chore: adds git checks for lesson 06 quiz

---

lesson_06/README.md

fix: updates doco to include missing command

---

.github/workflows/check_push.yml

fix: updates push action

---

lesson_06/expression/src/functions.ts
lesson_06/expression/src/lesson6.test.ts
lesson_06/expression/src/lesson6.ts
lesson_06/expression/src/utils.ts

chore: fix lint errors

---

lesson_05/khaylasaunders/README.md

Hi Mr. Mays, 
I have completed the assignment for lesson05 (user stories). Please let me know if I need to make any amendments. 
Best, 
Khayla

feat: Add user stories for Libby Library App

---

lesson_05/dadenaike'sGOODAM/README.md

**Changes to be committed: new file:   lesson_05/dadenaike'sGOODAM/README.md**

release/David.A lesson5hw/first submission

---

lesson_05/oliviajames/README.md

Submitting lesson 05 User Stories assignment.

Feat: Olivia James lesson 05

---

lesson_05/Bryana Singleton-Barnhart/README.md

Finished my User stories for lesson_05.

feat: finished lesson_05 homework

---

slides/src/Slides/Lessons/Lesson07.js

fix: corrects equivalent boolean expression

---

lesson_05/rmill_lesson_05/rm_README.md

Added unique directory and READ.md file with 3 user stories to complete homework for lesson_05

Feat: Rasheed Miller lesson_05

---

lesson_04/ananatawamcintyre/README.md

- Created a ReadMe.md utilizing both Python and JavaScript languages.
- The code helps the user or reader determine whether a number is a prime number or not. 
- File includes a brief summary of the similarities and differences between the Python and JavaScript implementations, along with a bonus message from the creator (me)! 
:-)

Feat: builds Nana's Prime Number Checker - README made with Python and JavaScript 

---

lesson_05/ananatawamcintyre/README.md

Pull requests containers a ReadMe.md of User Stories, Acceptance Criteria, and background on the software Reddit.

feat: adds Nana's Lesson05 README.md User Stories/Responses

---

lesson_05/JohnBey/README.md

Here's my user stories in my README.

Chore: Jbey Lesson 05 added user stories

---

lesson_04/oliviajames/README.md

chore: pushing lesson_04

---

lesson_04/meikostephens/README.md

completed my comparison readme

feat: add Meiko's lesson04

---

lesson_04/JBey/README.md

Hello Anthony, please tell me if I need to change anything. Thank you!

feat: JBey Lesson 04 complete.

---

lesson_04/khaylasaunders/README.md

Hi Mr. Mays, 
I completed my lesson04 write up!

feat KSaunders Readme04

---

lesson_04/Bryana Singleton-Barnhart/README.md

Completed observations for lesson 04 homework.

feat: complete lesson 04 homework

---

syllabus/README.md

chore: adds language workbench to syllabus

---

.github/workflows/check_lesson_09_pr.yaml

chore: add lesson_09 actions

---

slides/src/Slides/Lessons/Lesson11.js

chore: fixes malformed slide code

---

lesson_11/README.md

chore: adds reminder to format files

---

lesson_10/libraries/src/loaders/chanel_hutt_loader.ts
lesson_10/libraries/src/loaders/mercedes_mathews_loader.ts

chore: removes logging from Chanel's loader

---

slides/src/Slides/Lessons/Lesson16.js

chore: fix slides

---

lesson_21/README.md
lesson_22/README.md

feat: adds lesson_21 homework and lesson_22 pre-work

---

lesson_23/README.md
lesson_24/README.md

- **feat: adds lesson_23 homework and lesson_24 pre-work**
- **feat: adds lesson_23 homework and lesson_24 pre-work**

feat: adds lesson_23 homework and lesson_24 pre-work

---

lesson_24/README.md
lesson_25/README.md
syllabus/README.md

feat: adds lesson_24 work and lesson_25 pre-work

---

slides/src/Slides/Lessons/Lesson26.js

fix: corrects slide for lesson 26

---

lesson_26/api/java/api_app/build.gradle.kts

Lombok dependency was preventing people from initializing classes. The updated dependency fixes this problem

fix: lombok dependency update

---

lesson_24/README.md

docs: clarisifes lesson_24 requirements

---

lesson_28/README.md
lesson_28/db/db_app/build.gradle.kts

fix: adds assignment README update and fixes lombok issue

---

lesson_17/README.md

docs: updates requirement for clarity

---

syllabus/README.md

docs: fix links in syllabus

---

capstone/README.md

docs: clarifies 3P API requirement

---

slides/src/Slides/Lessons/Supplemental2.js
slides/src/Slides/Lessons/index.js
slides/src/Slides/Slides.js

feat: adds slides for supplemental lesson 2

---

.gitignore

chore: updates gitignore to include lecture notes
